Newsweek
Arinpe/Bootstrap pull request #1
Opened 2020-11-03 12:22 UTC by Arinpe

I walked alone on this project and I was able to achieve the clone of the Newsweek page using HTML, CSS and Bootstrap.

2020-11-03 13:26 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Arinpe Arinpe
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Fix the Linters errors
- [ ] The project is working fine locally but not online. Please Correct it. 
Instead of  `<link rel="stylesheet" type="text/css" href="/style.css">`
It should be `<link rel="stylesheet" type="text/css" href="./style.css">`
- [ ] Remove SVG from HTML file and save them in assets
- [ ] Fix HTML validation [HTML Validation Screenshort](https://user-images.githubusercontent.com/29689273/97987394-06073880-1dfd-11eb-8067-32d191b780c2.png). You can check HTML validations in [validator.w3.org](https://validator.w3.org/) ([screenshot](https://user-images.githubusercontent.com/29689273/94326203-fa358480-ffbb-11ea-81ec-b2704fb93212.png) from Pathwright)



### Navbar
- [ ] Logo is missing in the navbar, please add the logo with the navigation link

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://rawcdn.githack.com/Arinpe/Bootstrap/5c932ee480a2953d6db4f25fbe51d3be52b49a3c/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/97988639-18827180-1dff-11eb-86e5-eec5d34b3fd3.png)|![clone](https://user-images.githubusercontent.com/29689273/97988645-19b39e80-1dff-11eb-8b36-1a2c394fa713.png)|

### Navbar (small screen)
- [ ] Add the user icon
- [ ] Add the Logo with navigation link

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://rawcdn.githack.com/Arinpe/Bootstrap/5c932ee480a2953d6db4f25fbe51d3be52b49a3c/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/97988723-3a7bf400-1dff-11eb-813b-4bbb47d851c3.png)|![clone](https://user-images.githubusercontent.com/29689273/97988728-3bad2100-1dff-11eb-9f3e-4ff46c0544bb.png)|

### Header
- [ ] Article count should be one in small screens

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://rawcdn.githack.com/Arinpe/Bootstrap/5c932ee480a2953d6db4f25fbe51d3be52b49a3c/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/97988854-70b97380-1dff-11eb-9b56-f3ae28a910df.png)|![clone](https://user-images.githubusercontent.com/29689273/97988861-73b46400-1dff-11eb-9f0c-0a660e6c42d9.png)|

### Missing Image
- [ ] **IN THE MAGAZINE** image is missing, please add the image

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://rawcdn.githack.com/Arinpe/Bootstrap/5c932ee480a2953d6db4f25fbe51d3be52b49a3c/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/97988952-9fcfe500-1dff-11eb-82fc-b64e1d89348b.png)|![clone](https://user-images.githubusercontent.com/29689273/97988957-a1011200-1dff-11eb-9363-2edd087e8fea.png)|

### IN THE MAGAZINE section
- [ ] Please add the spacing using margin on other images as I explained in images

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://rawcdn.githack.com/Arinpe/Bootstrap/5c932ee480a2953d6db4f25fbe51d3be52b49a3c/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/97989120-e32a5380-1dff-11eb-9371-b4586d384ce1.png)|![clone](https://user-images.githubusercontent.com/29689273/97989130-e6254400-1dff-11eb-88fb-d8efd318d4c9.png)|

### SUBSCRIBE
- [ ] Update the design as source landing page

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://rawcdn.githack.com/Arinpe/Bootstrap/5c932ee480a2953d6db4f25fbe51d3be52b49a3c/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/97989411-516f1600-1e00-11eb-850d-e7699aee0915.png)|![clone](https://user-images.githubusercontent.com/29689273/97989419-53d17000-1e00-11eb-87a0-1bf4d18d818a.png)|


### NEWSLETTER
- [ ] Update the design as source landing page

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://rawcdn.githack.com/Arinpe/Bootstrap/5c932ee480a2953d6db4f25fbe51d3be52b49a3c/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/97989512-75325c00-1e00-11eb-8ba1-1a09068c43b6.png)|![clone](https://user-images.githubusercontent.com/29689273/97989518-782d4c80-1e00-11eb-9270-3b9c14640b32.png)|

### Footer (Small screen)
- [ ] Please add the Logo with the navigation link
- [ ] Manage the social media icons and other links like source page

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://rawcdn.githack.com/Arinpe/Bootstrap/5c932ee480a2953d6db4f25fbe51d3be52b49a3c/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/97989626-a0b54680-1e00-11eb-940b-11eefc7cb289.png)|![clone](https://user-images.githubusercontent.com/29689273/97989631-a317a080-1e00-11eb-98ad-3e399394f4af.png)|













##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-11-03 13:26 UTC, umairarshadbutt commented on index.html
> +  <link rel="stylesheet" type="text/css" href="/style.css">
Please update it as I mentioned in the review

2020-11-03 17:18 UTC, descholar-ceo requested changes
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @Arinpe  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] Your online link is not working, so please update it, since you are using githack, you can copy the `URL for development` which update itself whenever you push new codes, the one you copied is for production, consequently it didn't get updated when you changed the url for your styles link
- [ ] Make sure that all of the images use relative paths (the paths which start with a dot) so that they will work on any environment, currently most of your images are being missed online (not shown online) on the page because you are using wrong path pattern. Example: instead of writting `<img src="/assets/image.png"/>` it should be `<img src="./assets/image.png"/>`
- [ ] The mobile version of the clone should fill the whole screen, currently it's only taking a small part of the screen and stay skeezed on the left side of the screen
- [ ] The newsletter section should have the image on mobile screen, currently it's getting hidden
- [ ] Remember to use a red newsweek logo in the footer, currently you are using the black one
- [ ] I noticed that you are using a lot of `display: grid` in your css file, as this project is focusing mainly on bootstrap, you should take advantage of that, try to use bootstrap utility classes instead of using grid or flex. [This link might help you](https://getbootstrap.com/docs/4.3/layout/grid/)
# [Optional changes] :large_blue_circle: 
- [ ] Your commit messages should be in imperative mode or present tense, you should have used `Start the mark up on more stories` instead of `started the mark up on more stories`, refer [to this article for more details on how to write a good && professional commit message](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

If anything seems to be unclear to you, don't hesitate to contact me for more clarification slack: `@Mugirase Emmanuel` | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2020-11-04 08:54 UTC, Arinpe commented
The mobile version of the clone should fill the whole screen, currently, it's only taking a small part of the screen and stay squeezed on the left side of the screen. This part is displaying well on Mozilla firefox, I don't understand why it is not displaying well on chrome

2020-11-04 11:00 UTC, abredi requested changes
### Status: Require changes  ♲
Hi @Arinpe, 👏 You did very well on this project. ✨ Big-up for successfully replicating the Newsweek home page. Most requirements have done 👌, Kindly fix the following issues.

[REQUIRED]

- [ ] Update the live link in the readme file.
       You can use the following link [https://raw.githack.com/Arinpe/Bootstrap/newsweek/index.html](https://raw.githack.com/Arinpe/Bootstrap/newsweek/index.html)
- [ ] Set the avatars circle in the "The Debate" section.
- [ ] Set appropriate height and width for the Newsweek logo at the bottom of the page.
- [ ] Set the header position fixed.
- [ ] Fix the height of the cards in the "IN THE MAGAZINE" section. 

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/)

2020-11-04 14:25 UTC, Arinpe commented
- All the required changes have been fixed.

2020-11-04 15:39 UTC, mahmoud717 requested changes
### changes required
Hi guys, great job with the project so far. there are still some changes to be made.

### required

- [ ] Please adjust the position of the logo
![aasdasd](https://user-images.githubusercontent.com/60571499/98128212-4aa7d800-1ec0-11eb-95f7-214578846dcb.PNG)

- [ ] this story disappears in small large screed and doesn't look good in small
![sadsasd](https://user-images.githubusercontent.com/60571499/98128832-0ec14280-1ec1-11eb-9693-a7f6991bab25.PNG)

- [ ] please fix the spacings in the debate section.

 ![asdasdadada](https://user-images.githubusercontent.com/60571499/98128978-429c6800-1ec1-11eb-977c-d388efbad191.PNG)  

- [ ]  the image size is too big
![asgagaga](https://user-images.githubusercontent.com/60571499/98129294-a4f56880-1ec1-11eb-89c4-122d642d4f63.PNG)

- [ ] there is a whole section missing after the editor's picks section

---

please fix all of these issues and ask for another code review

2020-11-05 16:26 UTC, Arinpe commented
- The required section has been added. 
- All other changes have been fixe.

2020-11-05 17:09 UTC, descholar-ceo requested changes
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @Arinpe  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your clone looks like the original page and it is really nice, with all of changes that were required to make you finally achieved an outstanding clone congratulations on the good work you have done so far. 
:+1: I really wanted to approve this project but there is a small issue to fix before the approval,

# [Required Changes]
- [ ] The image on Subscribe section is overlapping with text on screens between (768px - 999px), please add spacing between them as the original page is, study the screenshot below to understand what I mean

| Your clone | Original page |
| --- | --- |
|![Screenshot from 2020-11-05 19-03-41](https://user-images.githubusercontent.com/56886064/98272478-cde92c80-1f99-11eb-9a33-f05ea12d1b86.png)|![Screenshot from 2020-11-05 19-05-48](https://user-images.githubusercontent.com/56886064/98272603-f2dd9f80-1f99-11eb-8b23-67c0e6254d5b.png)|
:point_right: Could you see the difference :question: :question: :question: 

If anything seems to be unclear to you, don't hesitate to contact me for more clarification slack: `@Mugirase Emmanuel` | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2020-11-09 14:14 UTC, mahmoud717 requested changes
### Changes requested 
**Hi guys**
Nice job implementing the required changes, but there are still some changes to be made:

- please fix all the linters issues before asking for another code review

2020-11-09 15:11 UTC, mimipeshy commented
## STATUS: APPROVED :champagne:  :dancers: 

Hi @Arinpe  :wave:  :wave: , great job on working on all comments given by the TSE's, I know it's a lot but great job for working on all of them. I, therefore, have to approve your project :partying_face:  . Go ahead and merge, all the best in the next project!

Regards
Peris Ndanu

2020-11-09 15:26 UTC, merged